### ISSUE TITLE
Naming of services & apps breaks networking capabilities

### ISSUE THREAD

**Issue by Malyuk-A** [oakestra/oakestra-net#168]
## Short
You can create and deploy apps and services with _ (underscores) in their names (e.g. "x_service", or "x_app"), however, the networking no longer works for them. I had a chat with @smnzlnsk and he found out that this is due to the mapping (most likely MQTT mapping, where special characters get turned into _ as dividers).

## Proposal
Due to the mentioned "mapping" a name like "app_x" gets interpreted as "app" / "x" which leads to unreachability.
See above, the bug itself is easy to replicate.
E.g. Take this working SLA: and change the app name to "app_X" or service name to "x_curl" and see for yourself.
```json
{
    "sla_version": "v2.0",
    "customerID": "Admin",
    "applications": [
        {
            "applicationID": "",
            "application_name": "appX",
            "application_namespace": "test",
            "application_desc": "Simple demo with curl client and Nginx server",
            "microservices": [
                {
                        "microserviceID": "",
                        "microservice_name": "curl",
                        "microservice_namespace": "test",
                        "virtualization": "container",
                        "cmd": ["sh", "-c", "curl 10.30.55.55 ; sleep 5"],
                        "memory": 100,
                        "vcpus": 1,
                        "vgpus": 0,
                        "vtpus": 0,
                        "bandwidth_in": 0,
                        "bandwidth_out": 0,
                        "storage": 0,
                        "code": "docker.io/curlimages/curl:7.82.0",
                        "state": "",
                        "port": "",
                        "added_files": [],
                        "one_shot": true,
                        "constraints":[]
                      },
                      {
                        "microserviceID": "",
                        "microservice_name": "nginx",
                        "microservice_namespace": "test",
                        "virtualization": "container",
                        "cmd": [],
                        "memory": 100,
                        "vcpus": 1,
                        "vgpus": 0,
                        "vtpus": 0,
                        "bandwidth_in": 0,
                        "bandwidth_out": 0,
                        "storage": 0,
                        "code": "docker.io/library/nginx:latest",
                        "state": "",
                        "port": "",
                        "addresses": {
                          "rr_ip": "10.30.55.55"
                        },
                        "added_files": [],
                        "constraints": []
                      }
                    ]
        }
    ]
}

```

## Solution 
Very easy solution: Restrict the naming of the services in the main app.
More complex solution: Figure out a way to allow "_" names - need to refactor "mapping" in networking.

## Status
Discussed. Need implementation/fixing.

## Checklist
- [x] Discussed
- [x] Replicated (Replicability)
- [ ] Solved
- [ ] Tested

**Comment by smnzlnsk** [comment]
Just to chime in on the bug we are having:
In the [https://github.com/oakestra/oakestra-net/blob/15c6470887c34d6ddfac519c6fde49daad316f2e/root-service-manager/service-manager/service_manager.py#L201](root service manager API) we are modifying the service name to be used based on the URI and take this modified service name for tablequery resolution. 

In the case there is an underscore in the service name itself, we erroneously replace the correct underscore with a false dot and try to resolve the tablequery. This of course fails, since the service names do not match anymore.

The easy fix would be imho, like Alexander already mentioned, to restrict special characters from being in the application and service name. 
This not only seems like the easy solution, but also insists on proper application and service naming according to our specifications.

We could therefore simply implement a regex matcher, which checks whether the application and service names pass the regex, and if not, refuse the deployment of the application.

**Comment by giobart** [comment]
1) we need to remove 8 characters limitations
2) we need to perform SLA validation for special characters (like . and / ) that should not end up in service names
3) return meaningful errors when this does not go trough
